const { Pokemon } = require('../models');

const pokemonData = [
  {
    pokemon_id: '1',
    name: 'Bulbasaur',
    level: '1',
    type: 'Grass',
    price: '750',
    trainer_id: '1',
    sprites: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
  },
  {
    pokemon_id: '2',
    name: 'Squirtle',
    _level: '1',
    _type: 'Water',
    price: '750',
    trainer_id: '2',
    _sprites: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
  },
  {
    pokemon_id: '3',
    name: 'Charmander',
    level: '1',
    type: 'Fire',
    price: '750',
    trainer_id: '3',
    sprites: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
  },
  {
    pokemon_id: '4',
    name: 'Eevee',
    level: '1',
    type: 'Normal',
    price: '1000',
    trainer_id: null,
    sprites: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png',
  },
  {
    pokemon_id: '5',
    name: 'Pikachu',
    level: '1',
    type: 'Electric',
    price: '1000',
    trainer_id: null,
    sprites: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
  },
  {
    pokemon_id: '6',
    name: 'Chikorita',
    level: '1',
    type: 'Grass',
    price: '500',
    trainer_id: null,
    sprites: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/152.png',
  },
  {
    pokemon_id: '7',
    name: 'Cyndaquil',
    level: '1',
    type: 'Fire',
    price: '500',
    trainer_id: null,
    sprites: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/155.png',
  },
  {
    pokemon_id: '8',
    name: 'Totodile',
    level: '1',
    type: 'Water',
    price: '500',
    trainer_id: null,
    sprites: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/158.png',
  },
  {
    pokemon_id: '9',
    name: 'Treecko',
    level: '1',
    type: 'Grass',
    price: '500',
    trainer_id: null,
    sprites: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/252.png',
  },
  {
    pokemon_id: '10',
    name: 'Torchic',
    level: '1',
    ptype: 'Fire',
    price: '500',
    trainer_id: null,
    sprites: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/255.png',
  },
  {
    pokemon_id: '11',
    name: 'Mudkip',
    level: '1',
    type: 'Water',
    price: '500',
    trainer_id: null,
    sprites: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/258.png',
  },
];

const seedPokemon = () => Pokemon.bulkCreate(pokemonData);

module.exports = seedPokemon;
